### PR TITLE
61-Use a cross-platform reference to HOME directory in config.py

### LINKED ISSUE #61: TypeError: expected str, bytes or os.PathLike object, not NoneType
**I have some issues about the example code. When I run the code below, it will report TypeError. Could you help me?**

- code:

```python
from txt2hpo.extract import Extractor
extract = Extractor()
result = extract.hpo("patient with developmental delay and hypotonia")
print(result.hpids)
````

- results

```python
Traceback (most recent call last):
  File "D:/PPD/2hpo.py", line 2, in <module>
    from txt2hpo.extract import Extractor
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\extract.py", line 7, in <module>
    from txt2hpo.build_tree import update_progress, hpo_network
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\build_tree.py", line 4, in <module>
    from txt2hpo.config import logger, config
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\txt2hpo\config.py", line 29, in <module>
    config_directory = os.path.join(os.environ.get('HOME'), f'.{__project__}')
  File "D:\ProgramData\Anaconda3\envs\python36\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
````

### PR DESCRIPTION
**Pull request by rebeccaito**
Closes #61

### CODE REVIEW

**Comment by rebeccaito** [comment]
@Vincent-Ustach know anyone who can approve this PR?

**Comment by Vincent-Ustach** [comment]
I could but I'm not confident in my opinion on your changes. @jamienoss  can you pls help Rebecca?

**Comment by rebeccaito** [comment]
Maybe @bennwei could review

**Review by jamienoss — APPROVED** [review]
Thanks for making the change! 👍

**Comment by jamienoss** [comment]
@rebeccaito do you need a release for this or are you ok with using develop for now?

**Pull request merged**
